# Generated by Django 3.0.3 on 2022-01-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('tourguide', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Duration', models.DurationField()),
                ('destination', models.CharField(max_length=100)),
                ('bill', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('categories', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='hotels',
            fields=[
                ('hotelId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=250)),
                ('rating', models.CharField(max_length=150)),
                ('price', models.PositiveIntegerField()),
                ('imageurl', models.URLField()),
                ('url', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('state', models.CharField(max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=250)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tourguide',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('languages', models.CharField(max_length=250)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=100)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speciality', to='TourApp.category')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='TourApp.status')),
            ],
        ),
        migrations.CreateModel(
            name='destinations',
            fields=[
                ('destinationId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField()),
                ('imageurl', models.URLField()),
                ('url', models.CharField(default='', max_length=100)),
                ('categori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='TourApp.category')),
            ],
        ),
    ]
