# Generated by Django 3.0.3 on 2022-02-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='photo',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourguide',
            name='photo',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
