# Generated by Django 3.0.3 on 2022-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0003_auto_20220203_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='hotels',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
