# Generated by Django 3.0.3 on 2022-02-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0004_auto_20220203_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hotels',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
