# Generated by Django 3.0.3 on 2022-02-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourApp', '0005_auto_20220203_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='longitude',
        ),
    ]
